apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: infra-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: "openstack:///'{{ instance_id }}'"
            kube-reserved: cpu=200m,memory=100Mi
            system-reserved: cpu=100m,memory=100Mi
          name: '{{ local_hostname }}'
          taints:
          - key: node-role.kubernetes.io/infra
            effect: NoSchedule
