apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: prow-control-plane
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: "openstack:///'{{ instance_id }}'"
          kube-reserved: cpu=200m,memory=100Mi
          system-reserved: cpu=100m,memory=100Mi
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: "openstack:///'{{ instance_id }}'"
          kube-reserved: cpu=200m,memory=100Mi
          system-reserved: cpu=100m,memory=100Mi
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
      kind: OpenStackMachineTemplate
      name: prow-control-plane-v1-26-6
  replicas: 1
  version: v1.26.6
