apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: prow
spec:
  apiServerLoadBalancer:
    enabled: true
    allowedCIDRs:
    - 10.6.0.0/24
  externalNetwork:
    id: df26cc5b-b122-4506-b948-a213d2b0a7d8
  identityRef:
    cloudName: prow
    name: prow-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: Calico - BGP
      direction: ingress
      etherType: IPv4
      name: BGP (calico)
      portRangeMax: 179
      portRangeMin: 179
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Calico IP-in-IP
      direction: ingress
      etherType: IPv4
      name: IP-in-IP (calico)
      protocol: "4"
      remoteManagedGroups:
      - controlplane
      - worker
    allowAllInClusterTraffic: false
  managedSubnets:
  - cidr: 10.6.0.0/24
    dnsNameservers:
    - 8.8.8.8
  bastion:
    enabled: true
    spec:
      flavor: c1m2
      image:
        filter:
          name: "Ubuntu-22.04-jammy"
      sshKeyName: metal3ci
