apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackCluster
metadata:
  name: prow
spec:
  apiServerLoadBalancer:
    enabled: true
    allowedCidrs:
    - 10.6.0.0/24
  cloudName: prow
  dnsNameservers:
  - 8.8.8.8
  externalNetworkId: fba95253-5543-4078-b793-e2de58c31378
  identityRef:
    kind: Secret
    name: prow-cloud-config
  managedSecurityGroups: true
  nodeCidr: 10.6.0.0/24
  bastion:
    enabled: true
    instance:
      flavor: 1C-2GB-50GB
      image: "Ubuntu 22.04.1 Jammy Jellyfish 230124"
      sshKeyName: metal3ci-key
