gitHubToken: "/etc/github/token"
skipPullRequest: false
gitHubOrg: "metal3-io"
gitHubRepo: "project-infra"
remoteName: "project-infra"
includedConfigPaths:
- "prow"
targetVersion: "latest"
prefixes:
- name: "k8s-prow images"
  prefix: "gcr.io/k8s-prow/"
  repo: "https://github.com/metal3-io/project-infra"
  summarise: false
extraFiles:
- "prow/Makefile"
