# See https://github.com/kubernetes-sigs/prow/blob/main/pkg/plugins/plugin-config-documented.yaml
owners:
  # By default, prow will use github org membership as the list of who is allowed to
  # /lgtm PRs.  This configuration setting tells it to use the OWNERS file only and
  # can be applied to a specific repo or entire github org.
  skip_collaborators:
  - "metal3-io"
plugins:
  Nordix:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - heart
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - pony
    - retitle
    - shrug
    - size
    - transfer-issue
    - trigger
    - verify-owners
    - wip
    - yuks
    - require-matching-label
    - override
  Nordix/metal3-clusterapi-docs:
  Nordix/metal3-dev-tools:
  Nordix/sles-ironic-python-agent-builder:
  metal3-io:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - heart
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - milestoneapplier
    - pony
    - retitle
    - shrug
    - size
    - transfer-issue
    - trigger
    - verify-owners
    - wip
    - yuks
    - require-matching-label
    - override
  metal3-io/.github:
  metal3-io/baremetal-operator:
  metal3-io/cluster-api-provider-metal3:
  metal3-io/community:
  metal3-io/ip-address-manager:
  metal3-io/ironic-hardware-inventory-recorder-image:
  metal3-io/ironic-image:
  metal3-io/ironic-agent-image:
  metal3-io/ironic-ipa-downloader:
  metal3-io/ironic-standalone-operator:
  metal3-io/mariadb-image:
  metal3-io/metal3-dev-env:
  metal3-io/metal3-docs:
  metal3-io/metal3-io.github.io:
  metal3-io/project-infra:
    plugins:
    - config-updater

approve:
- repos:
  - metal3-io
  - Nordix/metal3-clusterapi-docs
  - Nordix/metal3-dev-tools
  - Nordix/sles-ironic-python-agent-builder
  # RequireSelfApproval requires PR authors to explicitly approve their PRs.
  # Otherwise the plugin assumes the author of the PR approves the changes in the PR.
  require_self_approval: true

  # A /lgtm from a single approver should not allow a PR to merge.
  lgtm_acts_as_approve: false

blunderbuss:
  max_request_count: 2
  use_status_availability: true

external_plugins:
  Nordix/metal3-dev-tools:
  - name: needs-rebase
    # No endpoint specified implies "http://{{name}}".
    events:
    - pull_request
    # Dispatching issue_comment events to the needs-rebase plugin is optional. If enabled, this may cost up to two token per comment on a PR. If `ghproxy`
    # is in use, these two tokens are only needed if the PR or its mergeability changed.
    - issue_comment
  Nordix/metal3-clusterapi-docs:
  - name: needs-rebase
    # No endpoint specified implies "http://{{name}}".
    events:
    - pull_request
    # Dispatching issue_comment events to the needs-rebase plugin is optional. If enabled, this may cost up to two token per comment on a PR. If `ghproxy`
    # is in use, these two tokens are only needed if the PR or its mergeability changed.
    - issue_comment
  Nordix/sles-ironic-python-agent-builder:
  - name: needs-rebase
    events:
    - pull_request
    - issue_comment
  - name: cherrypicker
    events:
    - issue_comment
    - pull_request
    endpoint: http://cherrypicker
  metal3-io:
  - name: needs-rebase
    # No endpoint specified implies "http://{{name}}".
    events:
    - pull_request
    # Dispatching issue_comment events to the needs-rebase plugin is optional. If enabled, this may cost up to two token per comment on a PR. If `ghproxy`
    # is in use, these two tokens are only needed if the PR or its mergeability changed.
    - issue_comment
  - name: cherrypicker
    events:
    - issue_comment
    - pull_request
    endpoint: http://cherrypicker
config_updater:
  maps:
    # Update the config configmap whenever config.yaml changes
    prow/config/config.yaml:
      name: config
    # Update the plugins configmap whenever plugins.yaml changes
    prow/config/plugins.yaml:
      name: plugins
    # Update the label-config configmap whenever labels.yaml changes
    prow/config/labels.yaml:
      name: label-config
    # Update the job-config configmap whenever anything under jobs changes
    prow/config/jobs/**/*.yaml:
      name: job-config

require_matching_label:
# triage configuration
- missing_label: needs-triage
  org: metal3-io
  issues: true
  prs: false
  regexp: ^triage/accepted$
  missing_comment: |
    This issue is currently awaiting triage.
    If Metal3.io contributors determine this is a relevant issue, they will accept it by applying the `triage/accepted` label and provide further guidance.
    The `triage/accepted` label can be added by org members by writing `/triage accepted` in a comment.

override:
  allow_top_level_owners: true

triggers:
- repos:
  - metal3-io
  # Enable prow to trigger GitHub workflows.
  trigger_github_workflows: true

milestone_applier:
  metal3-io/cluster-api-provider-metal3:
    main: "CAPM3 - v1.12"
    release-1.11: "CAPM3 - v1.11"
    release-1.10: "CAPM3 - v1.10"
    release-1.9: "CAPM3 - v1.9"
    release-1.8: "CAPM3 - v1.8"
  metal3-io/baremetal-operator:
    main: "BMO - v0.12"
    release-0.11: "BMO - v0.11"
    release-0.10: "BMO - v0.10"
    release-0.9: "BMO - v0.9"
    release-0.8: "BMO - v0.8"
  metal3-io/ip-address-manager:
    main: "IPAM - v1.12"
    release-1.11: "IPAM - v1.11"
    release-1.10: "IPAM - v1.10"
    release-1.9: "IPAM - v1.9"
    release-1.8: "IPAM - v1.8"
  metal3-io/ironic-image:
    main: "ironic-image - v33.0"
    release-32.0: "ironic-image - v32.0"
    release-31.0: "ironic-image - v31.0"
    release-30.0: "ironic-image - v30.0"
    release-29.0: "ironic-image - v29.0"
    release-28.0: "ironic-image - v28.0"
    release-27.0: "ironic-image - v27.0"
    release-26.0: "ironic-image - v26.0"
  metal3-io/ironic-standalone-operator:
    main: "IrSO - v0.6"
    release-0.5: "IrSO - v0.5"
    release-0.4: "IrSO - v0.4"
