plugins:
  metal3-io/baremetal-operator:
  - size
  metal3-io/base-image:
  - size
  metal3-io/cluster-api-provider-baremetal:
  - size
  metal3-io/ironic-hardware-inventory-recorder-image:
  - size
  metal3-io/ironic-image:
  - size
  metal3-io/ironic-inspector-image:
  - size
  metal3-io/ironic-ipa-downloader:
  - size
  metal3-io/ironic-prometheus-exporter:
  - size
  metal3-io/metal3-dev-env:
  - size
  metal3-io/metal3-docs:
  - size
  metal3-io/metal3-helm-chart:
  - size
  metal3-io/metal3-io.github.io:
  - size
  metal3-io/metal3-smart-exporter:
  - size
  metal3-io/project-infra:
  - size
  metal3-io/prow-testing:
  - size
  metal3-io/static-ip-manager-image:
  - size
