apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  # ClusterIssuers are non-namespaced resources
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: estjorvas@est.tech
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: russell@russellbryant.net
          apiKeySecretRef:
            name: cloudflare-api-token-secret
            key: apikey
      selector: {}