apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubernetes/ingress-nginx/deploy/static/provider/cloud?ref=controller-v1.8.1
- cluster-issuer-http.yaml
- storageclass.yaml
- ingress-controller-pdb.yaml

patches:
- path: service.yaml
# Patch the ingress controller jobs with TTL to avoid issues when upgrading.
- path: ingress-controller-job-patch.yaml
  target:
    # Target all jobs in the namespace (overrides name/namespace in the patch file)
    kind: Job
    namespace: ingress-nginx
- path: ingress-controller-deployment-patch.yaml
