apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubernetes/ingress-nginx/deploy/static/provider/cloud?ref=controller-v1.7.0
- cluster-issuer-http.yaml
- storageclass.yaml

patches:
- path: service.yaml
