apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    loadbalancer.openstack.org/keep-floatingip: "true"
spec:
  loadBalancerIP: 89.46.86.136
  externalTrafficPolicy: Cluster
