apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prow
  name: cherrypicker
spec:
  template:
    spec:
      containers:
      - name: cherrypicker
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
