apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prow
  name: crier
spec:
  template:
    spec:
      containers:
      - name: crier
        resources:
          requests:
            cpu: 100m
            memory: 60Mi
