apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prow
  name: deck
spec:
  template:
    spec:
      containers:
      - name: deck
        resources:
          requests:
            cpu: 130m
            memory: 80Mi
