apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prow
  name: horologium
spec:
  template:
    spec:
      containers:
      - name: horologium
        resources:
          requests:
            cpu: 50m
            memory: 25Mi
