apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prow
  name: prow-controller-manager
spec:
  template:
    spec:
      containers:
      - name: prow-controller-manager
        resources:
          requests:
            cpu: 130m
            memory: 50Mi
