apiVersion: apps/v1
kind: Deployment
metadata:
  name: statusreconciler
  namespace: prow
spec:
  template:
    spec:
      containers:
      - name: statusreconciler
        resources:
          requests:
            cpu: 50m
            memory: 20Mi
