presubmits:
  metal3-io/cluster-api-provider-metal3:
  - name: metal3-centos-e2e-basic-test-release-1-8
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-basic-test-release-1-8
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-integration-test-release-1-8
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: false
  - name: metal3-ubuntu-e2e-integration-test-release-1-8
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-8-pivoting
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-8-remediation
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-8-features
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-8-pivoting
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-8-remediation
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-8-features
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-e2e-clusterctl-upgrade-test-release-1-8
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-e2e-1-29-1-30-upgrade-test-release-1-8
    branches:
    - release-1.8
    agent: jenkins
    always_run: false
    optional: true
