presubmits:
  metal3-io/ip-address-manager:
  - name: metal3-centos-e2e-basic-test-release-1-7
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-basic-test-release-1-7
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-integration-test-release-1-7
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-integration-test-release-1-7
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: false
  - name: metal3-centos-e2e-feature-test-release-1-7-pivoting
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-7-remediation
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-7-features
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-7-pivoting
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-7-remediation
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-7-features
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-e2e-clusterctl-upgrade-test-release-1-7
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-e2e-1-29-1-30-upgrade-test-release-1-7
    branches:
    - release-1.7
    agent: jenkins
    always_run: false
    optional: true
