presubmits:
  metal3-io/ironic-image:
  - name: shellcheck
    branches:
    - release-25.0
    run_if_changed: '((\.sh)|^Makefile)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/shellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/koalaman/shellcheck-alpine:v0.10.0@sha256:5921d946dac740cbeec2fb1c898747b6105e585130cc7f0602eec9a10f7ddb63
        imagePullPolicy: Always
  - name: markdownlint
    branches:
    - release-25.0
    run_if_changed: '(\.md|markdownlint\.sh)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/pipelinecomponents/markdownlint-cli2:0.12.0@sha256:a3977fba9814f10d33a1d69ae607dc808e7a6470b2ba03e84c17193c0791aac0
        imagePullPolicy: Always
  - name: metal3-centos-e2e-integration-test-release-1-8
    branches:
    - release-25.0
    agent: jenkins
    always_run: false
    optional: false
  - name: metal3-ubuntu-e2e-integration-test-release-1-8
    branches:
    - release-25.0
    agent: jenkins
    always_run: false
    optional: false
  - name: metal3-dev-env-integration-test-centos-release-1-8
    branches:
    - release-25.0
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-dev-env-integration-test-ubuntu-release-1-8
    branches:
    - release-25.0
    agent: jenkins
    always_run: false
    optional: true
