apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prow
  namespace: prow-monitoring
spec:
  replicas: 3
  image: docker.io/prom/alertmanager
  listenLocal: false
  nodeSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager
  version: v0.27.0
  storage: # Note that this section is immutable so changes require deleting and recreating the resource.
    volumeClaimTemplate:
      metadata:
        name: prometheus
      spec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager
  name: alertmanager
  namespace: prow-monitoring
spec:
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    alertmanager: prow
    app: alertmanager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: prow-monitoring
---
# TODO: NEED CHANGE HERE TO CORRECT SLACK SETTINGS
# Slack endpoint, or even different methods of alerting
# Please replace '{{ api_url }}' below with the URL of slack incoming hook
# before `kubectl apply -f`
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prow
  namespace: prow-monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 4h
      receiver: 'slack-warnings'
      routes:
      - receiver: 'cluster-api-aws-alerts'
        group_interval: 5m
        repeat_interval: 2h
        match:
          boskos_type: aws-account



    receivers:
    - name: 'slack-warnings'
      slack_configs:
      - channel: '#prow-alerts'
        api_url: '{{ api_url }}'
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        text: '{{ template "custom_slack_text" . }}'
        link_names: true

    templates:
    - '*.tmpl'
  msg.tmpl: |
    {{ define "custom_slack_text" }}{{ .CommonAnnotations.message }}{{ end }}
type: Opaque
