apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-control-plane-system
spec:
  version: v1.8.5
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-control-plane-system
