apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.16.0/cert-manager.yaml
- https://github.com/kubernetes-sigs/cluster-api-operator/releases/download/v0.14.0/operator-components.yaml
- core.yaml
- control-plane.yaml
- bootstrap.yaml
- infrastructure.yaml
