apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.yaml
- https://github.com/kubernetes-sigs/cluster-api-operator/releases/download/v0.19.0/operator-components.yaml
# ORC is needed for CAPO
- https://github.com/k-orc/openstack-resource-controller/releases/download/v2.1.0/install.yaml
- core.yaml
- control-plane.yaml
- bootstrap.yaml
- infrastructure.yaml

patches:
# Cert-manager does not set any toleration so we have to first create
# the array/map before we can add values to them...
- patch: |-
    - op: add
      path: /spec/template/spec/tolerations
      value: []
  target:
    kind: Deployment
    name: cert-manager|cert-manager-cainjector|cert-manager-webhook
    namespace: cert-manager
# CAPI operator does not set any nodeSelector
- patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: {}
  target:
    kind: Deployment
    name: capi-operator-controller-manager
    namespace: capi-operator-system
# ORC does not set either
- patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: {}
    - op: add
      path: /spec/template/spec/tolerations
      value: []
  target:
    kind: Deployment
    name: orc-controller-manager
    namespace: orc-system
# Add toleration and node selector to run on infra nodes
- path: toleration-node-selector-patch.yaml
  target:
    kind: Deployment
    name: cert-manager|cert-manager-cainjector|cert-manager-webhook
    namespace: cert-manager
- path: toleration-node-selector-patch.yaml
  target:
    kind: Deployment
    name: capi-operator-controller-manager
    namespace: capi-operator-system
- path: toleration-node-selector-patch.yaml
  target:
    kind: Deployment
    name: orc-controller-manager
    namespace: orc-system
