periodics:
- name: periodic-stale
  interval: 1h
  decorate: true
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/commenter:v20250306-095fc63a16
      command:
      - commenter
      args:
      - |-
        --query=org:metal3-io
        -label:lifecycle/frozen
        -label:lifecycle/stale
      - --updated=2160h
      - --token=/etc/token/token
      - |-
        --comment=Issues go stale after 90d of inactivity.
        Mark the issue as fresh with `/remove-lifecycle stale`.
        Stale issues will close after an additional 30d of inactivity.

        If this issue is safe to close now please do so with `/close`.

        /lifecycle stale
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/token
    volumes:
    - name: token
      secret:
        secretName: github-token
- name: periodic-stale-close
  interval: 1h
  decorate: true
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/commenter:v20250306-095fc63a16
      command:
      - commenter
      args:
      - |-
        --query=org:metal3-io
        -label:lifecycle/frozen
        label:lifecycle/stale
      - --updated=720h
      - --token=/etc/token/token
      - |-
        --comment=Stale issues close after 30d of inactivity. Reopen the issue with `/reopen`. Mark the issue as fresh with `/remove-lifecycle stale`.

        /close
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/token
    volumes:
    - name: token
      secret:
        secretName: github-token
- name: autobump-prow-images
  # At 00:00 on 1st every month
  cron: 0 0 1 * *
  decorate: true
  extra_refs:
  - org: metal3-io
    repo: project-infra
    base_ref: main
  spec:
    containers:
    - image: us-docker.pkg.dev/k8s-infra-prow/images/generic-autobumper:v20250709-d01b8af18
      command:
      - generic-autobumper
      args:
      - --config=prow/config/generic-autobumper-config.yaml
      - --signoff=true
      volumeMounts:
      - name: github-token
        mountPath: /etc/github
        readOnly: true
    volumes:
    - name: github-token
      secret:
        secretName: github-token
