apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: metal3-io
  namespace: openshift-ingress
spec:
  secretName: metal3-io-tls
  renewBefore: 720h # 30d
  commonName: '*.apps.ci.metal3.io'
  dnsNames:
  - metal3.io
  - '*.apps.ci.metal3.io'
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
