name: Scheduled Check Links

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 1 * *"
  repository_dispatch:
    # run manually
    types: [check-links]
  workflow_call:

permissions: {}

jobs:
  check-links:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

    - name: Link Checker
      id: linkcheck
      uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 # v2.6.1
      with:
        args: |
          --user-agent "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0"
          --root-dir "$(pwd)/"
          --fallback-extensions "md"
          --github-token "${GITHUB_TOKEN}"
          "./**/*.md"
        output: /tmp/lychee_output.md
        fail: false

    - name: Create Issue From File
      if: steps.linkcheck.outputs.exit_code != 0
      uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # v5.0.1
      with:
        title: Link Checker Report
        content-filepath: /tmp/lychee_output.md
        labels: |
          kind/bug
