---
- hosts: localhost
  connection: local
  environment:
    DHCP_HOSTS: "{{ DHCP_HOSTS }}"
    DHCP_IGNORE: "{{ DHCP_IGNORE }}"
  vars_files:
    - default_vars/vars.yaml
  tasks:
  - name: Deploy Bare Metal Lab
    block:
      - include_tasks: tasks/cleanup-tasks.yaml
      - include_tasks: tasks/deploy-tasks.yaml
