apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/projectcalico/calico/v3.30.1/manifests/calico.yaml
# Check available versions at https://github.com/kubernetes/cloud-provider-openstack/releases
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.32.0/manifests/controller-manager/cloud-controller-manager-roles.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.32.0/manifests/controller-manager/cloud-controller-manager-role-bindings.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.32.0/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.32.0/manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.32.0/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.32.0/manifests/cinder-csi-plugin/cinder-csi-nodeplugin-rbac.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.32.0/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.32.0/manifests/cinder-csi-plugin/csi-cinder-driver.yaml
- autoscaler.yaml
- coredns-pdb.yaml

images:
# Check available tags at https://github.com/kubernetes/autoscaler/tags
- name: registry.k8s.io/autoscaling/cluster-autoscaler
  newTag: v1.32.1

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- files:
  - cloud.conf
  name: cloud-config
  namespace: kube-system
  type: Opaque

patches:
# CSI Cinder does not set any toleration or nodeSelector so we have to first create
# the array/map before we can add values to them...
- patch: |-
    - op: add
      path: /spec/template/spec/tolerations
      value: []
    - op: add
      path: /spec/template/spec/nodeSelector
      value: {}
  target:
    kind: Deployment
    name: csi-cinder-controllerplugin
# Add toleration and node selector to run on infra nodes
- path: toleration-node-selector-patch.yaml
  target:
    kind: Deployment
    name: csi-cinder-controllerplugin|calico-kube-controllers
